### ISSUE TITLE
Does this script take into account user-script when rendering passages?

### ISSUE THREAD

**Issue by kctdfh** [tinwatchman/twinetojson#1]
Does this script take into account the user's custom Javascript? In the final HTML document it ends up in a <script> tag in <head> with id="twine-user-script". 

For e.g., I have this in my user-script: 
`document.foo = 'bar';`

and have this in one of my passages:
"After work, let's go to the `<%= document.foo %>`"

Would this passage end up in my JSON as:
"After work, let's go to the bar"

or as:
"After work, let's go to the <%= document.foo %>"

Thanks in advance!

**Comment by tinwatchman** [comment]
As I recall, this library doesn't touch the `<script>` tags inside of passages, since it's not really supposed to render the story. Instead, the whole idea here was to convert the story into a JSON format that could be easily turned into an AJAX/server-based application. It (optionally) handles some pre-rendering stuff -- like converting the markdown and links -- so that they won't have to be handled on the client side. But it otherwise leaves the actual content alone. Does that make sense?
